Add Plot.ly Graph to bottom of Submissions view
alexgriff/swbatnet pull request #1
Opened 2019-03-29 17:24 UTC by rishter

<img width="706" alt="Screen Shot 2019-03-29 at 1 17 13 PM" src="https://user-images.githubusercontent.com/552786/55251058-035a5f80-5226-11e9-92f9-bffdb95dde4c.png">

2019-04-06 23:01 UTC, alexgriff commented on lib/swbatnet_web/templates/submission/index.html.eex
> +<script>
Can we move this to another file that can run `import { App }` and run `makePlot` after the DOM content has loaded.

Just worried about ever being able to find this again if someone else wants to play around with it having it buried in the view like this

2019-04-06 23:02 UTC, alexgriff requested changes
Pending the one comment about moving the JS out of the script tag, good to go after that.

Thanks this is exciting!

2019-04-07 11:52 UTC, alexgriff commented
Page-specific js in phoenix https://stackoverflow.com/a/38169882

This example is way overengineered for this use case, but our version could be to add a conditional: is a certain dom node on the page, if so run the code to add the chart
https://medium.com/@hoang_nguyen/organize-and-serve-page-specific-javascript-in-phoenix-with-webpack-47a24d169c03

2021-03-10 14:53 UTC, rishter commented
miss u @alexgriff

2021-03-10 14:53 UTC, closed without merging